#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# M5 · 乱刃 v3 + accounts go to production. Run from the repo root:
#   bash scripts/m5-production-wizard.sh
# Nothing here writes secrets to the repo. The Resend key lives only in the
# Supabase Dashboard; Supabase keys live only in Vercel.

ENV_FILE=".env.local.production"   # your pre-M1 production .env.local (gitignored); used only to prefill prompts
PROJECT_REF="vzadfbhrjpwcqpdixuwk"
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
SITE_URL="https://www.moyufuns.com"
GAME_URL="https://games.moyufuns.com/games/slash/v3/index.html"
V3_BYTES=37508
TOTAL_STAGES=9

cd "$(dirname "$0")/.."

banner "MoYuFun · M5 production setup (accounts + 乱刃 v3)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Resend: verify moyufuns.com"
say "Verification and reset emails go out through Resend (D4)."
open_url "https://resend.com/domains"
step "Sign up / log in, then Add Domain → moyufuns.com (region: any)."
step "Resend shows DNS records: SPF (TXT), DKIM (TXT or CNAME ×3), optionally MX for bounces."
open_url "https://dash.cloudflare.com/"
step "Cloudflare → moyufuns.com → DNS → add every record Resend listed, exactly as shown (Proxy status: DNS only)."
step "Also add DMARC: TXT  _dmarc  →  v=DMARC1; p=none"
step "Back in Resend, click Verify. Wait until the domain shows Verified (can take a few minutes)."
pause "Press Enter once Resend shows the domain as Verified."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Resend API key → Supabase SMTP"
open_url "https://resend.com/api-keys"
step "Create API Key: name 'supabase-smtp', permission 'Sending access', domain 'moyufuns.com'. Copy it now; Resend never shows it again."
note "Do NOT paste it here or into any .env; it goes straight into Supabase."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/smtp"
step "Left nav: Authentication → Emails → 'SMTP Settings' tab → Enable Custom SMTP:"
say "    Sender email:  noreply@moyufuns.com"
say "    Sender name:   MoYuFun"
say "    Host:          smtp.resend.com"
say "    Port:          465"
say "    Username:      resend"
say "    Password:      <the Resend API key>"
step "Save."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/rate-limits"
step "Authentication → Rate Limits → 'Rate limit for sending emails' = 30 per hour (Resend free tier is 100/day). Save."
pause "Press Enter when SMTP is saved."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase Auth: URLs, password and confirmation policy"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/url-configuration"
step "Site URL:  ${SITE_URL}"
step "Redirect URLs → add:  ${SITE_URL}/auth/confirm   and   http://localhost:3000/auth/confirm"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Email provider → Enable Email provider ON, Confirm email ON, Secure email change ON, Secure password change ON."
step "Minimum password length 8, no character requirements (D15). Save."
note "If a setting is not on this page, look under Authentication → Sign In / Providers or Settings → Authentication in the left nav; the Dashboard moves things around."
pause "Press Enter when URL configuration and the email provider are saved."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase Auth: email templates"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/templates"
step "Confirm sign up → Subject: 验证你的 MoYuFun 邮箱 → Body (replace everything with):"
printf '\n'; sed 's/^/      /' supabase/templates/confirmation.html; printf '\n'
step "Reset password → Subject: 重置你的 MoYuFun 密码 → Body:"
printf '\n'; sed 's/^/      /' supabase/templates/recovery.html; printf '\n'
note "Both use {{ .TokenHash }} so /auth/confirm verifies server-side (D5). Save each template."
pause "Press Enter when both templates are saved."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel: server-only env vars"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/api-keys"
step "Copy the Publishable key (starts with sb_publishable_). Never the secret key."
open_url "https://vercel.com/dashboard"
step "Open the MoYuFun project → Settings → Environment Variables → add for Production (and Preview if you use it):"
say "    SUPABASE_URL              = ${SUPABASE_URL}"
say "    SUPABASE_PUBLISHABLE_KEY  = sb_publishable_…   (from the page that just opened)"
say "    SITE_URL                  = ${SITE_URL}"
warn "No NEXT_PUBLIC_ prefix on any of them (D3)."
pause "Press Enter when the three variables are saved in Vercel."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "R2: upload 乱刃 v3"
actual=$(wc -c < games/slash/v3/index.html | tr -d ' ')
if [[ "$actual" != "$V3_BYTES" ]]; then
  warn "games/slash/v3/index.html is ${actual} bytes but the publish migration asserts ${V3_BYTES}. Fix the migration's file_size_bytes first."
  exit 1
fi
say "Local file size matches the migration (${V3_BYTES} bytes)."
open_url "https://dash.cloudflare.com/"
step "Cloudflare → R2 → the bucket behind games.moyufuns.com → Upload → games/slash/v3/index.html"
step "Object key must be exactly:  games/slash/v3/index.html   (same layout as v2; v2 stays for rollback)."
pause "Press Enter once the upload finished."
say "Checking the CDN…"
for _ in 1 2 3 4 5 6; do
  code=$(curl -s -o /dev/null -w '%{http_code}' "$GAME_URL" || true)
  [[ "$code" == "200" ]] && break
  note "got HTTP ${code}; retrying in 10 s (CDN propagation)…"; sleep 10
done
if [[ "$code" != "200" ]]; then warn "Still HTTP ${code} at ${GAME_URL}. Fix the upload before continuing."; exit 1; fi
size=$(curl -s "$GAME_URL" | wc -c | tr -d ' ')
[[ "$size" == "$V3_BYTES" ]] || { warn "CDN serves ${size} bytes, expected ${V3_BYTES}. Wrong file?"; exit 1; }
curl -sI "$GAME_URL" | grep -iE '^(content-type|access-control-allow-origin|content-security-policy)' | sed 's/^/    /'
say "v3 is live on the CDN with the right size."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Supabase: push migrations (achievements + publish v3)"
say "This adds the achievement tables/functions and switches 乱刃 to v3 in production."
warn "Only continue if stage 6 succeeded: switching the current version before the file exists breaks /play/slash."
pnpm supabase db push --linked --dry-run
confirm "Dry run looks right (two new migrations)? Apply to production" || { warn "Aborted before push."; exit 1; }
pnpm supabase db push --linked
pnpm supabase db lint --linked --level warning
say "Migrations applied and lint is clean."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Deploy and revalidate"
step "Deploy main to Vercel the way you normally do (git push, or 'vercel --prod')."
pause "Press Enter once the production deployment is Ready."
for _ in 1 2 3 4 5 6; do
  body=$(curl -s "${SITE_URL}/api/me" || true)
  [[ "$body" == '{"user":null}' ]] && break
  note "/api/me returned '${body}'; retrying in 10 s…"; sleep 10
done
[[ "$body" == '{"user":null}' ]] || { warn "/api/me is not answering {\"user\":null}. Check the Vercel env vars from stage 5 and the deployment logs."; exit 1; }
say "/api/me is healthy (Supabase env vars work)."
ask_secret MOYUFUN_REVALIDATE_SECRET "Paste MOYUFUN_REVALIDATE_SECRET (same value as in Vercel):"
code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "${SITE_URL}/api/revalidate/games" -H "Authorization: Bearer ${MOYUFUN_REVALIDATE_SECRET}")
[[ "$code" == "200" ]] || { warn "Revalidate returned HTTP ${code}; check the secret."; exit 1; }
sleep 3
curl -s "${SITE_URL}/play/slash" | grep -q "games/slash/v3/index.html" && say "/play/slash now embeds v3." || warn "/play/slash does not reference v3 yet; wait a minute and reload."
curl -s "${SITE_URL}/games/slash" | grep -q "初见血" && say "/games/slash shows the 成就 section." || warn "/games/slash has no 成就 section yet; wait a minute and reload."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Production acceptance (M5 done-when)"
say "With a real mailbox, on ${SITE_URL}:"
step "注册 → the verification mail arrives from MoYuFun <noreply@moyufuns.com> (check spam once) → link lands on /me, header shows your email prefix."
step "退出 → 忘记密码 → reset mail → set a new password → 登录 with it."
step "Play 乱刃: 剑气 + 穿刺 loadout, win under 2 minutes without dying with a 5-kill streak → all six popups; /me shows 6 / 6 and /games/slash marks them."
step "Optional: 删除账号 with a throwaway account, then confirm /me redirects to /login."
say "Rollback if needed: switch current_version_id back to v2 via the publisher role and call /api/revalidate/games; v2 is still in R2."
pause "Press Enter when acceptance passed (or Ctrl-C to stop here)."

finish
say "Next: tell Claude 'M5 verified' so it ticks the milestone and runs M6 (docs)."
